image: archlinux
packages:
  - systemd
  - popt
  - libconfig
  - gsl
sources:
  - https://github.com/FedeDP/Clight
tasks:
  - build: |
      cd Clight
      make debug
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
