image: archlinux
packages:
  - systemd
  - popt
  - libconfig
  - gsl
  - cmake
sources:
  - https://github.com/FedeDP/Clight
tasks:
  - prepare: |
      cd Clight
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Debug ../
  - build: |
      cd Clight/build
      make
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
