sudo: required

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always

language: c

compiler:
  - gcc
  - clang

arch:
    packages:
        - systemd
        - popt
        - libconfig
        - gsl
    script:
        - "echo $CC"
        - make debug

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

