sudo: required

notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: never
    on_failure: always

language: c

compiler:
  - gcc
  - clang

arch:
    packages:
        - systemd
        - libxcb
        - popt
        - linux-api-headers
        - libx11
        - libxrandr
        - libconfig
    script:
        - "echo $CC"
        - make -C clight/ debug
        - make -C clightd/ debug
        - make -C clightd/ DISABLE_FRAME_CAPTURES=1 debug
        - make -C clightd/ DISABLE_GAMMA=1 debug
        - make -C clightd/ DISABLE_FRAME_CAPTURES=1 DISABLE_GAMMA=1 debug

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

